blank_issues_enabled: true
contact_links:
  - name: Contato ACDG (site)
    url: https://acdgbrasil.com.br/
    about: Fale com a ONG mantenedora
  - name: E‑mail (licença comercial/exceções)
    url: mailto:gabriel.aderaldo@acdgbrasil.com.br
    about: Solicite permissões comerciais ou tire dúvidas sobre licenças
